name: Continuos Delivery
on:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simular Continuos Delivery
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            main.py
            README.md